#!/bin/bash

pid=0

usage () {
	echo
	echo "-- Warning: Make sure you have a sudo permission --"
	echo
	echo "Flower Bridge: See Flowers fall on the bridge"
	echo "Every 15 minutes (default), all of your Flower Power will be update"
	echo 
	echo "USAGE: ./run cmd [delay]"
	echo
	echo "ARGUMENTS:"
	echo "	cmd:"
	echo "		display:	Lannch and show updating into your console"
	echo "		background:	Launch updatind to background. To know what happening: \`$ sudo ./updatedb\`"
	echo "		stop: 		Stop all processings and kill the program"
	echo
	echo "	delay (optional):"
	echo "		Specify the loop time in minute"
	echo
	echo "EXAMPLES:"
	echo "	sudo ./run display		: (loop every 15 minutes)"
	echo "	sudo ./run display 60		: (loop every 1 hour)"
	echo "	sudo ./run background 1440	: (loop every day without render in console)"
	echo
	echo "AUTHOR:"
	echo "	Written by Bruno Sautron."
}

welcome () {
	echo
	echo "-- Flower Bridge --"
	echo
}

displayit () {
	welcome
	node ./index.js $1 2> trace.log
	while [ "$?" == 111 ]; do
		echo "Crash into the program"
		echo "Restart the program"
		welcome
		node ./index.js $1 2> trace.log
	done
}

backgroundit () {
	welcome
	pid=$(head -n 1 ".flowerIsRunning" 2> /dev/null)
	if [ -z "$pid" ]
	then
		node ./index.js $1 2> trace.log 1>/dev/null &
		echo $! > ".flowerIsRunning"
		echo "To see your log:"
		echo "$> sudo ./updatedb"
	else
		echo "[$pid]: A program is already running"
	fi
}

stopit () {
	pid=$(head -n 1 ".flowerIsRunning" 2> /dev/null)
	if [ -z "$pid" ]
	then
		echo "No program is running"
	else
		killProgram
		echo "Bye :)"
	fi
}

restartit () {
	stopit
	backgroundit $1
}

killProgram () {
	kill $pid
	rm ".flowerIsRunning"
	echo "kill" $pid
	pid=0
}

if [ -z "$1" ]
then
	usage
else
	if [ "$1" == "display" ]
	then
		displayit $2 
	elif [ "$1" == "background" ]
	then
		backgroundit $2
	elif [ "$1" == "stop" ]
	then
		stopit $2
	elif [ $1 == "restart" ]
	then
		restartit
	else
		usage
	fi
fi
